// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
)

type Link struct {
	ID         int64
	ShortID    string
	Href       string
	CreatedAt  time.Time
	UsageCount int64
	UsageAt    time.Time
}
